version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  game-listing-api:
    build:
      context: .
    restart: always
    environment:
      APP_PORT: 3000
      DATABASE_URL: mongodb://root:rootpassword@mongodb:27017/
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  game-listing-ui:
    build:
      context: ../game-listing-ui
    restart: always
    ports:
      - 8080:80
volumes:
  mongodb_data_container:
